settings:
  ambient: "1.00~3.00"
  monsters: "4.00~8.50"
  # ###################
  players-percentage: 10
  # ###################
  premium-multiplier: 1.5

message:
  kill: "<dark_gray>[<gold>Убийство<dark_gray>] <white>На ваш баланс пополнено: %s монет"
